# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'JarvisGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisGUI(object):
    def setupUi(self, JarvisGUI):
        JarvisGUI.setObjectName("JarvisGUI")
        JarvisGUI.resize(993, 547)
        JarvisGUI.setStyleSheet("background-color: black;")
        JarvisGUI.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(JarvisGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 210, 551, 361))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Gifs/MImN.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(650, 210, 331, 241))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Gifs/7kmF.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 361, 271))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("Gifs/SUV4.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(720, 470, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:#0C5A9B;\n"
"color: #C2E0ED;\n"
"border-radius: 5px;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(610, 10, 381, 191))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Gifs/Jarvis_Loading_Screen.gif"))
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(850, 470, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:#0C5A9B;\n"
"color: #C2E0ED;\n"
"border-radius: 5px;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 310, 281, 221))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("border: none;\n"
                                       "color: white;\n"
                                       "font-size: 20px;\n")
        self.textBrowser.setObjectName("textBrowser")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 20, 181, 171))
        self.label_3.setText("")
        self.label_3.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_3.setPixmap(QtGui.QPixmap("Gifs/7fi4.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        JarvisGUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisGUI)
        QtCore.QMetaObject.connectSlotsByName(JarvisGUI)

    def retranslateUi(self, JarvisGUI):
        _translate = QtCore.QCoreApplication.translate
        JarvisGUI.setWindowTitle(_translate("JarvisGUI", "MainWindow"))
        self.pushButton.setText(_translate("JarvisGUI", "RUN"))
        self.pushButton_2.setText(_translate("JarvisGUI", "ABORT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisGUI = QtWidgets.QMainWindow()
    ui = Ui_JarvisGUI()
    ui.setupUi(JarvisGUI)
    JarvisGUI.show()
    sys.exit(app.exec_())
